from turtle import *
import turtle
a = turtle.Turtle()
b = a.clone()
c = b.clone()
d = c.clone()
a.screen.bgcolor("black")
a.screen.colormode(255)
a.screen.screensize(2000, 2000)
begin_fill()
while True:
    a.speed(0)
    a.pensize(15)
    a.color("red")
    a.forward(200)
    a.left(216)
    a.circle(100)
    b.speed(0)
    b.pensize(15)
    b.color("red")
    b.circle(50)
    b.penup()
    b.forward(200)
    b.pendown()
    b.circle(50)
    b.penup()
    b.left(216)
    b.pendown()
    b.circle(50)
    c.speed(0)
    c.pensize(15)
    c.color("red")
    c.penup()
    c.setposition(100, -330)
    c.pendown()
    c.circle(300)
    d.speed(0)
    d.pensize(15)
    d.color("red")
    d.penup()
    d.setposition(100, 400)
    d.left(90)
    d.pendown()
    d.forward(100)
    d.penup()
    d.setposition(-340, -300)
    d.left(90)
    d.pendown()
    d.left(45)
    d.forward(110)
    d.penup()
    d.setposition(550, -300)
    d.pendown()
    d.forward(110)
end_fill()
